version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "Kinesis2MSK"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ctbrpzhzyrm4"
s3_prefix = "Kinesis2MSK"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
